theme: nojekyll
title: RTIC UCL | Homepage
description: At RTIC we develop advanced image processing methodologies for radiotherapy applications. Our overarching aim is to exploit medical imaging to enable more accurate and safer radiotherapy treatments.
